import Mathlib
import sumcheck_soundness
import types

open BigOperators
open Classical Polynomial Finset

set_option autoImplicit true
set_option relaxedAutoImplicit true

variable {F : Type} [Field F] [Fintype F]
variable {Circuit Input Witness : Type}
variable {Ω : Type} [Fintype Ω]
variable (C : Circuit) (x : Input)
variable (eval : Circuit → Input → Witness → Bool)
variable {nc nv : ℕ}
variable (eps_FSK eps_sumcheck : ℕ)

/--
**Structure: IsFiatShamirTranscript**

Formalizes the structural non-adaptivity of a Fiat-Shamir transcript in an
interactive or non-interactive zero-knowledge proof.

In our combinatorial framework, non-adaptivity is expressed structurally:
1. `n`: The number of challenge rounds in the protocol ($n$).
2. `d`: The maximum polynomial degree in any round ($d$).
3. `P_func` & `p_func`: Strategies where round $i$ polynomials are functions `Prefix F i → RoundPoly F`, depending *only* on challenges `{r_0, ..., r_{i-1}}`. It is mathematically impossible for the prover's round $i$ polynomial to depend on challenge $r_i$ or any later challenges.

By enforcing this structure, we replace probability spaces and random oracle axioms with the combinatorial Fiat-Shamir theorem (`combinatorial_fiat_shamir`), proving that the number of challenge sequences leading to a cheating verifier acceptance is bounded by `n * d * |F|^(n-1)`.
-/
structure IsFiatShamirTranscript (F : Type) [Field F] (n d : ℕ) where
  P_func : TruePolyStrategy F n
  p_func : ProverStrategy F n
  hd : ∀ (i : Fin n) (pref : Prefix F i.val), (P_func i pref).natDegree ≤ d
  h1 : 1 ≤ d


/--
Proves that for any Fiat-Shamir transcript with maximum degree $d$ over $n$
rounds, the total number of cheating challenge sequences across all rounds
is bounded by `n * d * |F|^(n-1)`.
This directly applies `combinatorial_fiat_shamir` from `sumcheck_soundness.lean`.
-/
theorem combinatorial_fiat_shamir_soundness {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {n d : ℕ} (fs : IsFiatShamirTranscript F n d) :
  (Finset.filter (fun cs : Fin n → F => any_bad_event n fs.P_func fs.p_func cs) Finset.univ).card ≤ n * d * (Fintype.card F)^(n - 1) := by
  exact combinatorial_fiat_shamir n d fs.P_func fs.p_func fs.hd fs.h1


/--
**Definition: Sumcheck Correlation Predicate (`R_sumcheck`)**

The specific binary relation between a prover's non-adaptive strategy `(P_func, p_func)`
and a verifier's challenge sequence `cs : Fin n → F` that a cheating prover
attempts to satisfy in an `n`-round Fiat-Shamir protocol.

A challenge sequence `cs` satisfies `R_sumcheck` if and only if 
at least one round's polynomial difference has `cs i` as a root.

-/
def R_sumcheck (F : Type) [Field F] (n : ℕ) (P_func : TruePolyStrategy F n) (p_func : ProverStrategy F n) (cs : Fin n → F) : Prop :=
  any_bad_event n P_func p_func cs


/--
**Structure: IsCorrelationIntractable**

Formalizes the Correlation Intractability (CI) assumption for Fiat-Shamir hash
functions specifically tailored to our zero-knowledge proof.

In Fiat-Shamir, challenges are generated by a cryptographic hash function $H$
applied to the transcript.
An adversary wins if they can produce an execution $\omega \in \Omega$ where
the transcript challenges satisfy the cheating correlation `R_sumcheck`.

A hash function is **correlation intractable** for `R_sumcheck` if no prover
can find an execution $\omega$ satisfying `R_sumcheck` with greater chance
than a uniformly random choice of challenge sequence would satisfy `R_sumcheck`:

1. `n`: The number of rounds in the protocol.
2. `d`: The maximum degree of any round polynomial.
3. `fs`: The underlying non-adaptive Fiat-Shamir transcript strategy (`IsFiatShamirTranscript F n d`).
4. `hash_ci_bound`: Pinpoints the correlation intractability property: the number of executions
   in $\Omega$ satisfying `R_sumcheck` is bounded by `eps_sumcheck`.
-/
structure IsCorrelationIntractable (F : Type) [Field F] [Fintype F] [DecidableEq F]
  (n d : ℕ) (fs : IsFiatShamirTranscript F n d) (challenge_map : Ω → (Fin n → F)) (eps_sumcheck : ℕ) where
  hash_ci_bound : event_card (Finset.filter (fun ω => R_sumcheck F n fs.P_func fs.p_func (challenge_map ω)) Finset.univ) ≤ eps_sumcheck


theorem uniform_hash_is_correlation_intractable {F : Type} [Field F] [Fintype F] [DecidableEq F]
    {n d : ℕ} (fs : IsFiatShamirTranscript F n d) (challenge_map : Ω → (Fin n → F)) (K : ℕ)
    (h_unif : ∀ (cs : Fin n → F), (Finset.filter (fun ω => challenge_map ω = cs) Finset.univ).card ≤ K) :
    IsCorrelationIntractable F n d fs challenge_map (K * (n * d * (Fintype.card F)^(n - 1))) := by
  constructor
  dsimp [event_card]
  have h_comp := card_filter_comp challenge_map (R_sumcheck F n fs.P_func fs.p_func)
  rw [h_comp]
  have h_le : ∑ y ∈ Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ, (Finset.filter (fun x => challenge_map x = y) Finset.univ).card ≤
    ∑ y ∈ Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ, K := by
    apply Finset.sum_le_sum
    intro cs _
    exact h_unif cs
  have h_sum_const : ∑ y ∈ Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ, K =
    (Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ).card * K := by
    simp [Finset.sum_const, mul_comm]
  have h_fs : (Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ).card ≤ n * d * (Fintype.card F)^(n - 1) := by
    -- dsimp [R_sumcheck]
    exact combinatorial_fiat_shamir_soundness fs
  calc ∑ y ∈ Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ, (Finset.filter (fun x => challenge_map x = y) Finset.univ).card
    _ ≤ ∑ y ∈ Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ, K := h_le
    _ = (Finset.filter (R_sumcheck F n fs.P_func fs.p_func) Finset.univ).card * K := h_sum_const
    _ ≤ (n * d * (Fintype.card F)^(n - 1)) * K := by
      gcongr
    _ = K * (n * d * (Fintype.card F)^(n - 1)) := by ring
