add_test([=[FFT.Inverse]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fft_test [==[--gtest_filter=FFT.Inverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FFT.Inverse]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FFT.Linear]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fft_test [==[--gtest_filter=FFT.Linear]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FFT.Linear]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FFT.Impulse]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fft_test [==[--gtest_filter=FFT.Impulse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FFT.Impulse]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FFT.RootOfUnity]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fft_test [==[--gtest_filter=FFT.RootOfUnity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FFT.RootOfUnity]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FFT.Shift]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fft_test [==[--gtest_filter=FFT.Shift]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FFT.Shift]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  fft_test_TESTS FFT.Inverse FFT.Linear FFT.Impulse FFT.RootOfUnity FFT.Shift)
