if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/fft_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/fft_test[1]_tests.cmake")
else()
  add_test(fft_test_NOT_BUILT fft_test_NOT_BUILT)
endif()
