if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/fp2_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/fp2_test[1]_tests.cmake")
else()
  add_test(fp2_test_NOT_BUILT fp2_test_NOT_BUILT)
endif()
