if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/fp_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/fp_test[1]_tests.cmake")
else()
  add_test(fp_test_NOT_BUILT fp_test_NOT_BUILT)
endif()
