add_test([=[Fp.AllSizes]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fp_test [==[--gtest_filter=Fp.AllSizes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Fp.AllSizes]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Fp.SmallField]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fp_test [==[--gtest_filter=Fp.SmallField]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Fp.SmallField]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Fp.RootOfUnity]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fp_test [==[--gtest_filter=Fp.RootOfUnity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Fp.RootOfUnity]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Fp.InverseSecp256k1]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fp_test [==[--gtest_filter=Fp.InverseSecp256k1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Fp.InverseSecp256k1]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Fp.castable]=]  /workspaces/longfellow-zk/clang-build-release/algebra/fp_test [==[--gtest_filter=Fp.castable]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Fp.castable]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  fp_test_TESTS Fp.AllSizes Fp.SmallField Fp.RootOfUnity Fp.InverseSecp256k1 Fp.castable)
