if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/nat_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/nat_test[1]_tests.cmake")
else()
  add_test(nat_test_NOT_BUILT nat_test_NOT_BUILT)
endif()
