if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/poly_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/poly_test[1]_tests.cmake")
else()
  add_test(poly_test_NOT_BUILT poly_test_NOT_BUILT)
endif()
