if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/rfft_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/rfft_test[1]_tests.cmake")
else()
  add_test(rfft_test_NOT_BUILT rfft_test_NOT_BUILT)
endif()
