if(EXISTS "/workspaces/longfellow-zk/clang-build-release/algebra/sysdep_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/algebra/sysdep_test[1]_tests.cmake")
else()
  add_test(sysdep_test_NOT_BUILT sysdep_test_NOT_BUILT)
endif()
