if(EXISTS "/workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test[1]_tests.cmake")
else()
  add_test(lch14_test_NOT_BUILT lch14_test_NOT_BUILT)
endif()
