add_test([=[LCH14.WAdditivity]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.WAdditivity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.WAdditivity]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LCH14.WRecursion]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.WRecursion]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.WRecursion]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LCH14.WHat]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.WHat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.WHat]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LCH14.Twiddle]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.Twiddle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.Twiddle]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LCH14.Interpolation]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.Interpolation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.Interpolation]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[LCH14.BidirectionalFFT]=]  /workspaces/longfellow-zk/clang-build-release/gf2k/lch14_test [==[--gtest_filter=LCH14.BidirectionalFFT]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[LCH14.BidirectionalFFT]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  lch14_test_TESTS LCH14.WAdditivity LCH14.WRecursion LCH14.WHat LCH14.Twiddle LCH14.Interpolation LCH14.BidirectionalFFT)
