if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/base64/decode_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/base64/decode_test[1]_tests.cmake")
else()
  add_test(decode_test_NOT_BUILT decode_test_NOT_BUILT)
endif()
