add_test([=[ZKTest.prover_verifier]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZKTest.prover_verifier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZKTest.prover_verifier]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZKTest.failing_test]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZKTest.failing_test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZKTest.failing_test]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZKTest.short_proofs_fail]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZKTest.short_proofs_fail]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZKTest.short_proofs_fail]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZKTest.random_proofs_fail]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZKTest.random_proofs_fail]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZKTest.random_proofs_fail]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZKTest.elt_out_of_range]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZKTest.elt_out_of_range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZKTest.elt_out_of_range]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZK.test_circuit_io]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZK.test_circuit_io]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZK.test_circuit_io]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ZK.Rfc_testvector1]=]  /workspaces/longfellow-zk/clang-build-release/zk/zk_test [==[--gtest_filter=ZK.Rfc_testvector1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ZK.Rfc_testvector1]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/zk SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  zk_test_TESTS ZKTest.prover_verifier ZKTest.failing_test ZKTest.short_proofs_fail ZKTest.random_proofs_fail ZKTest.elt_out_of_range ZK.test_circuit_io ZK.Rfc_testvector1)
