add_test([=[CBOR.DecodeOneV8]=]  /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/cbor_test [==[--gtest_filter=CBOR.DecodeOneV8]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CBOR.DecodeOneV8]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CBOR.VerifyDecode]=]  /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/cbor_test [==[--gtest_filter=CBOR.VerifyDecode]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CBOR.VerifyDecode]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CBOR.VerifyParseSize]=]  /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/cbor_test [==[--gtest_filter=CBOR.VerifyParseSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CBOR.VerifyParseSize]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  cbor_test_TESTS CBOR.DecodeOneV8 CBOR.VerifyDecode CBOR.VerifyParseSize)
