if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/mso2_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/mso2_test[1]_tests.cmake")
else()
  add_test(mso2_test_NOT_BUILT mso2_test_NOT_BUILT)
endif()
