if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/mso_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/cbor_parser/mso_test[1]_tests.cmake")
else()
  add_test(mso_test_NOT_BUILT mso_test_NOT_BUILT)
endif()
