if(EXISTS "/workspaces/longfellow-zk/clang-build-release/proto/circuit_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/proto/circuit_test[1]_tests.cmake")
else()
  add_test(circuit_test_NOT_BUILT circuit_test_NOT_BUILT)
endif()
