if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/anoncred/small_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/anoncred/small_test[1]_tests.cmake")
else()
  add_test(small_test_NOT_BUILT small_test_NOT_BUILT)
endif()
