if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/compiler/compiler_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/compiler/compiler_test[1]_tests.cmake")
else()
  add_test(compiler_test_NOT_BUILT compiler_test_NOT_BUILT)
endif()
