add_test([=[Sumcheck.EvalCircuit]=]  /workspaces/longfellow-zk/clang-build-release/sumcheck/sumcheck_test [==[--gtest_filter=Sumcheck.EvalCircuit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sumcheck.EvalCircuit]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/sumcheck SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sumcheck.SumcheckAddE]=]  /workspaces/longfellow-zk/clang-build-release/sumcheck/sumcheck_test [==[--gtest_filter=Sumcheck.SumcheckAddE]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sumcheck.SumcheckAddE]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/sumcheck SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sumcheck.SumcheckAddEOneCopy]=]  /workspaces/longfellow-zk/clang-build-release/sumcheck/sumcheck_test [==[--gtest_filter=Sumcheck.SumcheckAddEOneCopy]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sumcheck.SumcheckAddEOneCopy]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/sumcheck SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sumcheck.RandomCircuit]=]  /workspaces/longfellow-zk/clang-build-release/sumcheck/sumcheck_test [==[--gtest_filter=Sumcheck.RandomCircuit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sumcheck.RandomCircuit]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/sumcheck SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  sumcheck_test_TESTS Sumcheck.EvalCircuit Sumcheck.SumcheckAddE Sumcheck.SumcheckAddEOneCopy Sumcheck.RandomCircuit)
