if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/sha/flatsha256_circuit_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/sha/flatsha256_circuit_test[1]_tests.cmake")
else()
  add_test(flatsha256_circuit_test_NOT_BUILT flatsha256_circuit_test_NOT_BUILT)
endif()
