if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/jwt/jwt_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/jwt/jwt_test[1]_tests.cmake")
else()
  add_test(jwt_test_NOT_BUILT jwt_test_NOT_BUILT)
endif()
