if(EXISTS "/workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test[1]_tests.cmake")
else()
  add_test(elliptic_curve_test_NOT_BUILT elliptic_curve_test_NOT_BUILT)
endif()
