add_test([=[EllipticCurve.isOnCurve]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.isOnCurve]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.isOnCurve]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEZeroA]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEZeroA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEZeroA]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEZeroA]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEZeroA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEZeroA]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEMinus3A]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEMinus3A]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEMinus3A]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEMinus3A]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEMinus3A]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEMinus3A]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEGeneral]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEGeneral]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEGeneral]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEGeneral]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEGeneral]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEGeneral]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.P256MultiExponentiation]=]  /workspaces/longfellow-zk/clang-build-release/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.P256MultiExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.P256MultiExponentiation]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  elliptic_curve_test_TESTS EllipticCurve.isOnCurve EllipticCurve.addEZeroA EllipticCurve.doubleEZeroA EllipticCurve.addEMinus3A EllipticCurve.doubleEMinus3A EllipticCurve.addEGeneral EllipticCurve.doubleEGeneral EllipticCurve.P256MultiExponentiation)
