if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test[1]_tests.cmake")
else()
  add_test(bit_plucker_test_NOT_BUILT bit_plucker_test_NOT_BUILT)
endif()
