add_test([=[Logic.Assert0]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Assert0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Assert0]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.Simple]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Simple]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Simple]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.Scan]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Scan]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Scan]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.AddSub]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.AddSub]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.AddSub]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.Comparison]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Comparison]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Comparison]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.Multiplier]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Multiplier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Multiplier]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.AssertSum]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.AssertSum]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.AssertSum]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.GF2PolynomialMultiplier]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.GF2PolynomialMultiplier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.GF2PolynomialMultiplier]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.GF2_128Multiplier]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.GF2_128Multiplier]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.GF2_128Multiplier]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logic.Bitvec]=]  /workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_test [==[--gtest_filter=Logic.Bitvec]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logic.Bitvec]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  logic_test_TESTS Logic.Assert0 Logic.Simple Logic.Scan Logic.AddSub Logic.Comparison Logic.Multiplier Logic.AssertSum Logic.GF2PolynomialMultiplier Logic.GF2_128Multiplier Logic.Bitvec)
