if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_circuit_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/logic/logic_circuit_test[1]_tests.cmake")
else()
  add_test(logic_circuit_test_NOT_BUILT logic_circuit_test_NOT_BUILT)
endif()
