if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/logic/memcmp_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/logic/memcmp_test[1]_tests.cmake")
else()
  add_test(memcmp_test_NOT_BUILT memcmp_test_NOT_BUILT)
endif()
