if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/logic/polynomial_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/logic/polynomial_test[1]_tests.cmake")
else()
  add_test(polynomial_test_NOT_BUILT polynomial_test_NOT_BUILT)
endif()
