name = "formal_circuits"
version = "0.1.0"
# defaultTargets = ["ECDSA", "pk_circuit", "lfzk"]
defaultTargets = ["lfzk"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
path = "../../mathlib4"
rev = "v4.31.0"

[[lean_lib]]
name = "ECDSA"
srcDir = "circuits"
globs = ["ECDSA.+"]

[[lean_lib]]
name = "pk_circuit"
srcDir = "circuits/tests/ec"
roots = ["PkCircuit", "PkCircuitPoly"]

[[lean_lib]]
name = "quadcert"
srcDir = "circuits"
globs = ["quadcert.+"]

[[lean_lib]]
name = "lfzk"
srcDir = "lfzk"
roots = ["types", "fiat_shamir", "circuit", "ligero", "ligero_rs", "ligero_sys", "ligero_bridge", "mlin", "lfzk", "sumcheck_soundness", "layers", "builder", "instantiate", "zk_layers", "zk_soundness", "zk_hiding", "zk_sim", "example"]

[[lean_lib]]
name = "merkle"
srcDir = "merkle"
roots = ["Heap", "Merkle", "Collision", "Wire", "RandomOracle", "Binding", "Hiding", "Instantiate"]
