add_test([=[MerkleTree.BuildTree]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.BuildTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.BuildTree]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.GenProof]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.GenProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.GenProof]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.VerifyProof]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.VerifyProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.VerifyProof]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.VerifyCompressedProof]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.VerifyCompressedProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.VerifyCompressedProof]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.VerifyCompressedProofFailure]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.VerifyCompressedProofFailure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.VerifyCompressedProofFailure]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.ZeroLengthProof]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.ZeroLengthProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.ZeroLengthProof]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.BatchVerifyProofTooShort]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.BatchVerifyProofTooShort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.BatchVerifyProofTooShort]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.TestVectors]=]  /workspaces/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.TestVectors]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.TestVectors]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  merkle_tree_test_TESTS MerkleTree.BuildTree MerkleTree.GenProof MerkleTree.VerifyProof MerkleTree.VerifyCompressedProof MerkleTree.VerifyCompressedProofFailure MerkleTree.ZeroLengthProof MerkleTree.BatchVerifyProofTooShort MerkleTree.TestVectors)
