add_test([=[HostDecoderTest.DecodeHost]=]  /workspaces/longfellow-zk/clang-build-release/cbor/host_decoder_test [==[--gtest_filter=HostDecoderTest.DecodeHost]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HostDecoderTest.DecodeHost]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/cbor SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HostDecoderTest.Lookup]=]  /workspaces/longfellow-zk/clang-build-release/cbor/host_decoder_test [==[--gtest_filter=HostDecoderTest.Lookup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HostDecoderTest.Lookup]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/cbor SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  host_decoder_test_TESTS HostDecoderTest.DecodeHost HostDecoderTest.Lookup)
