if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test[1]_tests.cmake")
else()
  add_test(mdoc_zk_test_NOT_BUILT mdoc_zk_test_NOT_BUILT)
endif()
