add_test([=[MdocZKTest.one_claim]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.one_claim]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.one_claim]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.two_claims]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.two_claims]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.two_claims]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.wrong_witness]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.wrong_witness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.wrong_witness]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.bad_arguments]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.bad_arguments]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.bad_arguments]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.attr_mismatch]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.attr_mismatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.attr_mismatch]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.bad_proofs]=]  /workspaces/longfellow-zk/clang-build-release/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.bad_proofs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.bad_proofs]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  mdoc_zk_test_TESTS MdocZKTest.one_claim MdocZKTest.two_claims MdocZKTest.wrong_witness MdocZKTest.bad_arguments MdocZKTest.attr_mismatch MdocZKTest.bad_proofs)
