if(EXISTS "/workspaces/longfellow-zk/clang-build-release/circuits/ecdsa/verify_external_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/circuits/ecdsa/verify_external_test[1]_tests.cmake")
else()
  add_test(verify_external_test_NOT_BUILT verify_external_test_NOT_BUILT)
endif()
