add_test([=[Transcript.Write]=]  /workspaces/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.Write]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.TwoBlocks]=]  /workspaces/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.TwoBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.TwoBlocks]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.Associative]=]  /workspaces/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.Associative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.Associative]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.GenArrayChallenge]=]  /workspaces/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.GenArrayChallenge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.GenArrayChallenge]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.TestVec]=]  /workspaces/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.TestVec]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.TestVec]=]  PROPERTIES WORKING_DIRECTORY /workspaces/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  transcript_test_TESTS Transcript.Write Transcript.TwoBlocks Transcript.Associative Transcript.GenArrayChallenge Transcript.TestVec)
