if(EXISTS "/workspaces/longfellow-zk/clang-build-release/random/transcript_test[1]_tests.cmake")
  include("/workspaces/longfellow-zk/clang-build-release/random/transcript_test[1]_tests.cmake")
else()
  add_test(transcript_test_NOT_BUILT transcript_test_NOT_BUILT)
endif()
